# Site settings
title: new Blog();
email: s@muel.be
description: "A blog by Samuel Debruyn where he posts about his daily life as a software developer."
baseurl: ""
twitter_username: SamuelDebruyn
github_username:  SamuelDebruyn

# Build settings
markdown: kramdown
permalink: pretty
future: false
show_drafts: false
limit_posts: 0
highlighter: pygments
pygments: true
exclude: [vendor]

# Kramdown settings
kramdown:
 input: GFM
 coderay_line_numbers: inline
