# Site settings
title: new Blog();
email: s@muel.be
description: "A blog by Samuel Debruyn where he posts about his daily life as a software developer."
baseurl: ""
url: "http://blog.sa.muel.be"
twitter_username: SamuelDebruyn
github_username:  SamuelDebruyn

# Build settings
markdown: kramdown
permalink: pretty
future: false
show_drafts: false
limit_posts: 0
highlighter: pygments

# Kramdown settings
kramdown:
 input: GFM

# Default settings
defaults:
 -
  scope:
   path: ""
  values:
   author: "Sam"