# Site settings
title: new Blog();
email: s@muel.be
description: "A blog by Samuel Debruyn where he posts about his daily life as a software developer."
baseurl: ""
twitter_username: SamuelDebruyn
github_username:  SamuelDebruyn

# Build settings
markdown: kramdown
permalink: pretty
future: false
show_drafts: false
limit_posts: 0
pygments: false
exclude: [vendor]

# Kramdown settings
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: table
    coderay_css: class
