# Site settings
title: Sam's blog
email: s@muel.be
description: "A blog by Samuel Debruyn where he posts about his daily life as a software developer."
baseurl: ""
permalink: /:year/:title/
display_name: Samuel Debruyn
twitter_username: SamuelDebruyn
github_username:  SamuelDebruyn
github_repo: https://github.com/SamuelDebruyn/samueldebruyn.github.io
url: http://sa.muel.be
limit_posts: 0

# Build settings
markdown: kramdown
encoding: utf-8
future: false
show_drafts: false
highlighter: pygments
exclude: [vendor]

# Kramdown settings
kramdown:
  use_coderay: false

# Sitemap settings
sitemap:
  include_posts:
      - "index.html"
      - "posts.html"
